apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16.1-alpine3.19
        imagePullPolicy: Always
        ports:
        - name: tcp
          containerPort:  5432
        env:
        - name: POSTGRES_USER
          value: quarkus
        - name: POSTGRES_PASSWORD
          value: quarkus
        - name: POSTGRES_DB
          value: quarkus
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: postgresqlserv
spec:
  ports:
    - name: pgsql
      protocol: TCP
      port:  5432
      targetPort:  5432
  type: ClusterIP
  selector:
    app: postgresql